name: custom_lint
version: 0.6.4
description: Lint rules are a powerful way to improve the maintainability of a project. Custom Lint allows package authors and developers to easily write custom lint rules.
repository: https://github.com/invertase/dart_custom_lint
issue_tracker: https://github.com/invertase/dart_custom_lint/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.6.0
  analyzer_plugin: ^0.11.0
